town_list = {

    1: 'Kikinda Centar', 
    2: 'Novi Sad Rumenačka', 
    3: 'Novi Sad Liman', 
    4: 'Beočin Centar', 
    5: 'Sremska Mitrovica', 
    6: 'Pančevo Sodara', 
    7: 'Beograd Stari grad', 
    9: 'Beograd Novi Beograd', 
    10: 'Beograd Mostar', 
    11: 'Beograd Vračar', 
    12: 'Beograd Zeleno brdo', 
    13: 'Šabac', 
    14: 'Kostolac', 
    15: 'Smederevo Centar', 
    16: 'Obrenovac Centar', 
    17: 'Smederevo Carina', 
    22: 'Valjevo', 
    23: 'Bor Krivelj-ZIJIN', 
    24: 'Bor Brezonik', 
    25: 'Bor Gradski park', 
    26: 'Bor Institut RIM', 
    27: 'Kragujevac', 
    28: 'Kosjerić', 
    29: 'Popovac ', 
    30: 'Zaječar', 
    31: 'Čačak ', 
    32: 'Paraćin', 
    33: 'Užice', 
    34: 'Kraljevo', 
    35: 'Kruševac', 
    36: 'Kamenički Vis EMEP', 
    37: 'Niš O.š. Sveti Sava', 
    38: 'Niš IZJZ Niš', 
    39: 'Kopaonik', 
    40: 'Vranje', 
    41: 'Subotica ', 
    42: 'Kikinda', 
    43: 'Sombor ', 
    45: 'Novi Sad Šangaj ', 
    46: 'Deliblatska peščara', 
    47: 'Obedska bara ', 
    56: 'Pančevo Cara Dušana', 
    57: 'Pančevo Vatrogasni dom', 
    58: 'Pančevo Vojlovica', 
    59: 'Pančevo Starčevo', 
    67: 'Bor Slatina-ZIJIN', 
    71: 'Novi Pazar', 
    73: 'Vršac'
    
    }



